---
- name: Provision of instances
  hosts: all
  become: yes

  tasks:

  - name: Create instance1
    ec2:
      key_name: mykey
      instance_type: t2.micro
      image: ami-0f7cd40eac2214b37
      group: builder
      count: 1

  - name: Add a host alias that we reach through a tunnel (Ansible 2.0 and newer)
    add_host:
      hostname: '{{ maven }}'
      ansible_host: '{{ maven }}'
      ansible_port: '{{ 23 }}'

  - name: Create instance2
    ec2:
      key_name: mykey
      instance_type: t2.micro
      image: ami-0f7cd40eac2214b37
      group: prod
      count: 1

  - name: Add a host alias that we reach through a tunnel (Ansible 2.0 and newer)
    add_host:
      hostname: '{{ web }}'
      ansible_host: '{{ web }}'
      ansible_port: '{{ 24 }}'